config/routes.rb
Rails.application.routes.draw do
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'welcome/say_hello' => 'welcome#say'
  get 'welcome' => 'welcome#index'
  root to: 'welcome#index'
  resources :events do
    resources :attendees, controller: 'event_attendees'
    resource :location, controller: 'event_locations'
  end
  resources :events do
    collection do
      get :latest
      post :bulk_delete
    end
  end
  resources :events do
    member do
      get :dashboard
    end
  end
  # match ':controller(/:action(/:id(.:format)))', via: :all
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :event
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name
  has_many :attendees, dependent: :destroy
  belongs_to :category, optional: true
  has_one :location, dependent: :destroy
  has_many :event_groupships
  has_many :groups, through: :event_groupships
  delegate :name, to: :category, prefix: true, allow_nil: true
  accepts_nested_attributes_for :location, allow_destroy: true, reject_if: :all_blank
end

app/models/event_groupship.rb
class EventGroupship < ApplicationRecord
  belongs_to :event
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :event_groupships
  has_many :events, through: :event_groupships
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :event
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :find_event
  def index
    @attendees = @event.attendees
  end

  def show
    @attendee = @event.attendees.find(params[:id])
  end

  def new
    @attendee = @event.attendees.build
  end

  def create
    @attendee = @event.attendees.build(attendee_params)
    if @attendee.save
      redirect_to event_attendees_url(@event)
    else
      render action :new
    end
  end

  def edit
    @attendee = @event.attendees.find(params[:id])
  end

  def update
    @attendee = @event.attendees.find(params[:id])
    if @attendee.update(attendee_params)
      redirect_to event_attendees_url
    else
      render action :edit
    end
  end

  def destroy
    @attendee = @event.attendees.find(params[:id])
    @attendee.destroy
    redirect_to event_attendees_url(@event)
  end

  protected

    def find_event
      @event = Event.find(params[:event_id])
    end

    def attendee_params
      params.require(:attendee).permit(:name)
    end
end

app/controllers/event_locations_controller.rb
class EventLocationsController < ApplicationController
  before_action :find_event

  def show
    @location = @event.location
  end

  def new
    @location = @event.build_location
  end

  def create
    @location = @event.build_location(location_params)
    if @location.save
      redirect_to event_location_url(@event)
    else
      render action :new
    end
  end

  def edit
    @location = @event.location
  end

  def update
    @location = @event.location
    if @location.update(location_params)
      redirect_to event_location_url
    else
      render action :edit
    end
  end

  def destroy
    @location = @event.location
    @location.destroy
    redirect_to event_location_url(@event)
  end

  protected

    def find_event
      @event = Event.find(params[:event_id])
    end

    def location_params
      params.require(:location).permit(:name)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  def index
    @events = Event.all
    # @events = Event.page(params[:page]).per(5)
    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.xml { render xml: @events.to_xml }
    #   format.json { render json: @events.to_json }
    #   format.atom { @feed_title = 'My event list' } # index.atom.builder
    sort_by = params[:order] == 'name' ? 'name' : 'created_at'
    @events = Event.order(sort_by).page(params[:page]).per(5)
  end

  def new
    @event = Event.new
  end

  def show
    @page_title = @event.name
    respond_to do |format|
      format.html { @page_title = @event.name } # show.html.erb
      format.xml # show.xml.builder
      format.json { render json: { id: @event.id, name: @event.name }.to_json }
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      flash[:notice] = 'event was successfully updated'
      redirect_to event_url(@event)
    else
      render action: :edit
    end
  end

  def destroy
    @event.destroy
    flash[:alert] = 'event was successfully deleted'
    redirect_to events_url
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = 'event was successfully created'
      redirect_to events_url
    else
      render action: :new
    end
  end

  def latest
    @events = Event.order("id DESC").limit(3)
  end

  def bulk_delete
    Event.destroy_all
    redirect_to events_path
  end

  def dashboard
    @event = Event.find(params[:id])
  end

  private

    def event_params
      params.require(:event).permit(:name, :description, :category_id,
        location_attributes: [:id, :name, :_destroy], group_ids: [])
    end

    def set_event
      @event = Event.find(params[:id])
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def say; end

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/event_locations_helper.rb
module EventLocationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def setup_event(event)
    event.build_location unless event.location
    event
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/event_attendees/edit.html.erb
<%= form_for @attendee, :url =>  event_attendee_path(@event, @attendee), :html => { :method => :patch } do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/event_attendees/index.html.erb
<ul>
<% @attendees.each do |attendee| %>
	<li>
		<%= attendee.name %>
		<%= link_to 'show', event_attendee_path(@event, attendee) %>
		<%= link_to 'edit', edit_event_attendee_path(@event, attendee) %>
		<%= button_to 'destory', event_attendee_path(@event, attendee), :method => :delete, data: { confirm: 'Are you sure?' } %>
	</li>
<% end %>
</ul>
<%= link_to 'new', new_event_attendee_path(@event) %>
<%= link_to 'back', events_path %>

app/views/event_attendees/new.html.erb
<%= form_for @attendee, :url =>  event_attendees_path(@event) do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/event_attendees/show.html.erb
<p><%= @attendee.name %> </p>

app/views/event_locations/edit.html.erb
<%= form_for @location, :url => event_location_path(@event), :method => :patch do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/event_locations/new.html.erb
<%= form_for @location, :url => event_location_path(@event) do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/event_locations/show.html.erb
<h1><%= @event.name %></h1>

<% if @event.location %>
	<p><%= @event.location.name %></p>
	<p><%= link_to "edit", edit_event_location_path(@event) %></p>
	<p><%= button_to "destory", event_location_path(@event), :method => :delete %></p>
<% else %>
	<p>N/A</p>
	<p><%= link_to "Add location", new_event_location_path(@event) %></p>
<% end %>

app/views/events/_form.html.erb
<%= f.label :name, "Name" %>
<%= f.text_field :name %>
<%= f.label :description, "Description" %>
<%= f.text_area :description %>
<%= f.collection_select(:category_id, Category.all, :id, :name) %>
<%= f.collection_check_boxes(:group_ids, Group.all, :id, :name) %>
<%= f.fields_for :location do |location_form| %>
	<p>
	<%= location_form.label :name, "Location Name" %>
	<%= location_form.text_field :name %>

	<% unless location_form.object.new_record? %>
		<%= location_form.label :_destroy, 'Remove:' %>
		<%= location_form.check_box :_destroy %>
	<% end %>
	</p>
<% end %>



<% if @event.errors.any? %>
	<ul>
	<% @event.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>

app/views/events/dashboard.html.erb
<%= @event.name %>
<p>This is dashboard</p>

app/views/events/edit.html.erb
<%= form_for setup_event(@event), :url => event_path(@event), :method => :put do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
	<%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<ul>
<%= link_to 'Sort by Name', events_path( :order => "name") %>
<%= link_to 'Sort by Default', events_path %>
<% @events.each do |event| %>
	<li>
	<%= event.name %>
    <%= link_to 'Show', event_path(event)%>
    <%= link_to 'Edit', edit_event_path(event)%>
	<%= link_to " (XML)", event_path(event, :format => :xml) %>
    <%= link_to " (JSON)", event_path(event, :format => :json) %>
    <%= button_to 'Delete', event_path(event), :method => :delete, :data => { :confirm => "Are you sure?" } %>
	<%= link_to 'attendees', event_attendees_path(event) %>
	<%= link_to 'location', event_location_path(event) %>
	<%= link_to 'Dashboard', dashboard_event_path(event) %>
	</li>
<% end %>
</ul>
<%= paginate @events %>
<%= button_to "Delete All", bulk_delete_events_path, :method => :post %>
<%= link_to 'New Event', :controller => 'events', :action => 'new' %>
<%= link_to "Atom feed", events_path(:format => :atom) %>

app/views/events/new.html.erb
<%= form_for setup_event(@event), :url => events_path do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
	<%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>
<p>Category: <%= @event.category.try(:name) %></p>
<p>Group:
	<% @event.groups.each do |g| %>
		<%= g.name %>
	<% end %>
</p>
<p><%= link_to 'Back to index', events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Event application" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:alert] %></p>
<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.label :birthday, style: "display: block" %>
    <%= form.date_field :birthday %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Name:</strong>
    <%= person.name %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= person.bio %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= person.birthday %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>People</h1>

<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Show this person", person %>
    </p>
  <% end %>
</div>

<%= link_to "New person", new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>

app/views/welcome/index.html.erb
<p>Hola! It's <%= Time.now %></p>
<p><%= link_to 'Hello!', welcome_say_hello_path %></p>

app/views/welcome/say.html.erb
<h1>Hello, World!</h1>
<p><%= link_to "Home", root_path %></p>